# DigitalOcean App Platform - Static Site
# TravelAxis is built as a static export (Next.js output: 'export').
name: travelaxiss
static_sites:
  - name: travelaxiss
    github:
      repo: mrjaved121/travelaxiss
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build
    output_dir: out
    routes:
      - path: /
